#cloud-config
ssh_authorized_keys: 
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAuvWTzLsty7RLfptx2+pM6eP1Sr9i6vu263+fnb+p5p1mttT5RoUm48SWJikPT28TPe4OjG159XP6NaqceRXbBKs98nRKJAuNWNXLG5SmTbYV3ihs2I9GTVhkuUGbg6vBjoRfvHTdXxtXzzU5YIzFeMQJjeuloyLdYz9PF2PSs7CFvYBnpgNdMjyxfoMajNGNP2B8sz5zHzaLO4gsvJJOljiAG+TWQH2G3GMdLwu/TM9JJmefOyjDyiYIVpmQgHYRZkM96hHpdoTSvqs/rTIJKwhcTElHbXzsrQ5a52XAfnQ66HdqOxhxuagqeNE2GSh2jPUS3U3pGHQI+ptSYw9/qw==
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA81RAYpMGoaqQ5kGpyxQH0tmjgkS2IxxpLnuXfjY/I54ndWRrDb1g1zmFvQJ8Qw6AO9XSDstktFUz9YeWA7y73dzx/miixcOIzQNC3Y4LSt/jrg1WtMaF6L1wZxmoGl9zG7dXQL7C4Hd6LPnF62fy1S9FWPd4OUjb9HnLt7xxTtRBkZEwjaySi1GvtFGBBjRZwc1/EcfZT5j7fgwROCHVBY8pNF0myu7iYc5yIUCjw5+b/1Y93hN9JIXTO4mx/kOrXiN0J1i7jvPa9jjrihH7fXO9lr6aHDthFhUaybkfHI+y8BJlARp0KYplphrILSOZ8Qb+THC/BF0dCMcy2oBdZQ==
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2QVBi8oUp8PV7pAhlZt6CB3jIgqP40Z3p0van3R1uVfe0533Z/3UUz/un3XGtzNyHZK8AZxtnfmfe7bnlFgHWYcpnYb4gS58oc1kUHeJDCAZ+63w9Ov0SYGvXraaN1V4Of4zOVv9vN329qM9drRpjugKzzr6VNI+hIlNCmzKw6JHEwhsl1LKc/7uEiaL1BxTqi9e2SHx1y6WCnlBFb8pRvbjxvSnneuwsLy0uzSFDoFIZILPD9TADvNXF12WDKuDjjMwQr5Ks2YQwX3jHb5IUIlquQropgXYYCXv3rw585o7xqxxjZU8sKKk8X5kxgRDu32L5CUOaGxkvIeTRExHb
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAiqwvWST0bHc8qKn1acg7BQXttmoCOlz1caN++dow2EbFBawsqw9KC7u8cHtBpKdLzZrJG/NyaowxVGfb2+ySKCSumpOnEypL2oIiEHAe4EaBqScQ9OEgETan0Xbll0+5ovG5DIbSQe97T+6xtWIYf1YaVZCcnf57t/4/aPN81jk=
rancher:
  console: ubuntu
  docker:
    engine: docker-17.03.2-ce
  state:
    fstype: auto
    dev: LABEL=RANCHER_STATE
hostname: castor