#cloud-config
hostname: aedile
ssh_authorized_keys: 
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC2QVBi8oUp8PV7pAhlZt6CB3jIgqP40Z3p0van3R1uVfe0533Z/3UUz/un3XGtzNyHZK8AZxtnfmfe7bnlFgHWYcpnYb4gS58oc1kUHeJDCAZ+63w9Ov0SYGvXraaN1V4Of4zOVv9vN329qM9drRpjugKzzr6VNI+hIlNCmzKw6JHEwhsl1LKc/7uEiaL1BxTqi9e2SHx1y6WCnlBFb8pRvbjxvSnneuwsLy0uzSFDoFIZILPD9TADvNXF12WDKuDjjMwQr5Ks2YQwX3jHb5IUIlquQropgXYYCXv3rw585o7xqxxjZU8sKKk8X5kxgRDu32L5CUOaGxkvIeTRExHb
  - ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAIEAiqwvWST0bHc8qKn1acg7BQXttmoCOlz1caN++dow2EbFBawsqw9KC7u8cHtBpKdLzZrJG/NyaowxVGfb2+ySKCSumpOnEypL2oIiEHAe4EaBqScQ9OEgETan0Xbll0+5ovG5DIbSQe97T+6xtWIYf1YaVZCcnf57t/4/aPN81jk=
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQCj0YFDtbUgrvbQUDcfbWNZXk7yvBsSna3cB7vYsHFuprLtcBk5V5XvE6merk7i9FqrcrEsE0Y4gGjwszfw6BzuFe4b6ofj6eGzti/uppSpfKmCKvaKzWDKcwjQM5CYwZU+3RM7fRVF+UmlhbvCFiq6SvcK5tUMXtJP2qQFOtGdrivP8HVwJvOmQMEDfx8yPrhwuM52bgO8He9ltPmBp+utcIyBUMALuCzh1QdnGov/MIo6ev/Rr06Up7gkU15SMNDkQ9oi30xM/uNn31uFAH/IrQ566Gn2Y9EhnJdQzkVppaVx7rN23uDl3TIQtaeM7wwbLe0VPaig+Y0L73cIpQwYldt/2CSJrk8KGNvEJzrfbW0nSAFsEMlXEdeFUuOUMh5bQDAsKR+cFW/KNht+mcbJwXuyVup0kB1jmeoeDcrKexFwhQ462UqMlOZBTHmd2ZETQKb3xI29QVkZzuBsTt+fgaEaA615CRsW5i8ifKhZiwnNtuNluL+T+j0HYyViHpA6asYeUEWtU13I0+oSeLIO/iSdB6uKYj5rAfQF2xOrOyRw4zdUpYc2uWEk/a14hk/1oX92Zs/kfD20d7JTqYF4LPXM+crBjm5GNHCy7atP4A0ociq7A+rR/Ckc3A3EbUj6SE+uDnfR5HdZzJYV/mqhvXvJoj6DEwj4RdaaUxWe5w==
rancher:
  cloud_init:
    datasources:
    - url:https://raw.githubusercontent.com/WritheM/rome-config/master/aedile/cloud-config.yml
  console: ubuntu
  resize_device: /dev/sda
  services_include:
    qemu-guest-agent: true
    kernel-headers: true
  state:
    dev: LABEL=RANCHER_STATE
    fstype: auto
    wait: true
  network:
    interfaces:
      "mac=00:22:06:00:10":
        dhcp: true
      "mac=00:22:06:00:11":
        address: 10.52.1.21
        netmask: 255.255.255.224
        dhcp: false
packages:
 - nfs-kernel-server